name: ${PROJECT_NAME}-${PROJECT_ENVIRONNEMENT}
services:
  app:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}:${PROJECT_ENVIRONNEMENT}
    container_name: ${PROJECT_NAME}-${PROJECT_ENVIRONNEMENT}
    ports:
      - "${PROJECT_PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PLASMIC_PROJECT_ID=${NEXT_PUBLIC_PLASMIC_PROJECT_ID}
      - NEXT_PUBLIC_PLASMIC_PROJECT_TOKEN=${NEXT_PUBLIC_PLASMIC_PROJECT_TOKEN}
      - NEXT_PUBLIC_SUPABASE_ID=${NEXT_PUBLIC_SUPABASE_ID}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    networks:
      - ${PROJECT_NAME}-network
    restart: unless-stopped

networks:
 jam-network:
    name: ${PROJECT_NAME}-network
    driver: bridge
    external: true